import { Box, Button, Input, Link, VStack, Text } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import React, { FormEvent, useState } from "react";
import styles from "../styles/Home.module.css";
import { checkIfBdayIsLucky } from "../utils/luckyCalculator";

export default function Home() {
  const [luckyNumber, setLuckyNumber] = React.useState(
    Math.floor(Math.random() * 100)
  );
  const [birthDay, setBirthDay] = useState(new Date());
  const [isLucky, setIsLucky] = React.useState(false);
  const [isLuckyVisible, setIsLuckyVisible] = React.useState(false);

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    console.log(luckyNumber, birthDay.getDate());
    setIsLucky(checkIfBdayIsLucky(birthDay, luckyNumber));
    setIsLuckyVisible(true);
    console.log(checkIfBdayIsLucky(birthDay, luckyNumber));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>The Lucky Birthday</h1>

        <p className={styles.description}>Check if your b&apos;day is lucky.</p>
        <Box bg="blue.100" p="5" rounded="10">
          <VStack
            align="center"
            justify="center"
            alignItems="center"
            justifyContent="center"
          >
            <Input
              variant="filled"
              required
              m="2"
              type="date"
              onChange={(e) => setBirthDay(new Date(e.target.value))}
            />
            <Input
              m="2"
              required
              type="number"
              variant="filled"
              value={luckyNumber}
              onChange={(e) => setLuckyNumber(parseInt(e.target.value))}
            />
            <Button
              variant="solid"
              colorScheme="messenger"
              onClick={handleSubmit}
            >
              Check
            </Button>
            <Button variant="ghost" colorScheme="messenger">
              Reset
            </Button>
            {isLuckyVisible && (
              <>
                <Text>
                  {" "}
                  {isLucky
                    ? "Yay!! Your Birthday is Lucky"
                    : "Sorry! You missed it."}
                </Text>
                {isLucky ? (
                  <Image
                    src="https://media.giphy.com/media/YnBntKOgnUSBkV7bQH/giphy.gif"
                    alt="Happy Gif"
                    height={100}
                    width={100}
                  />
                ) : (
                  <Image
                    src="https://media.giphy.com/media/BEob5qwFkSJ7G/giphy.gif"
                    alt="Happy Gif"
                    height={100}
                    width={100}
                  />
                )}
              </>
            )}
          </VStack>
        </Box>
      </main>
      <footer className={styles.footer}>
        <Link href="https://kishans.in" target="_blank">
          Built by Kishan
        </Link>
      </footer>
    </div>
  );
}
